namespace EmployeesManager.Domain.Constants
{
    public static class LocalizationKeys
    {
        // Common
        public const string ENTRY_NOT_FOUND = "ENTRY_NOT_FOUND";
        public const string ENTRY_REMOVE_SUCCESS = "ENTRY_REMOVE_SUCCESS";
        public const string ENTRY_UNREMOVE_SUCCESS = "ENTRY_UNREMOVE_SUCCESS";
        public const string ENTRY_CREATE_SUCCESS = "ENTRY_CREATE_SUCCESS";
        public const string ENTRY_UPDATE_SUCCESS = "ENTRY_UPDATE_SUCCESS";
        public const string INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";

        // Emolyee
        public const string EMPLOYEE_FIRST_NAME_FIELD_REQUIRED = "EMPLOYEE_FIRST_NAME_FIELD_REQUIRED";
        public const string EMPLOYEE_FIRST_NAME_GREATER_MAX_LENGTH = "EMPLOYEE_FIRST_NAME_GREATER_MAX_LENGTH";
        public const string EMPLOYEE_LAST_NAME_FIELD_REQUIRED = "EMPLOYEE_LAST_NAME_FIELD_REQUIRED";
        public const string EMPLOYEE_LAST_NAME_GREATER_MAX_LENGTH = "EMPLOYEE_LAST_NAME_GREATER_MAX_LENGTH";
        public const string EMPLOYEE_PATRONYMIC_FIELD_REQUIRED = "EMPLOYEE_PATRONYMIC_FIELD_REQUIRED";
        public const string EMPLOYEE_PATRONYMIC_GREATER_MAX_LENGTH = "EMPLOYEE_PATRONYMIC_GREATER_MAX_LENGTH";
        public const string EMPLOYEE_DEPARTMENT_FIELD_REQUIRED = "EMPLOYEE_DEPARTMENT_FIELD_REQUIRED";
        public const string EMPLOYEE_BIRTHDAY_FIELD_REQUIRED = "EMPLOYEE_BIRTHDAY_FIELD_REQUIRED";
        public const string EMPLOYEE_EMPLOYMENT_DATE_FIELD_REQUIRED = "EMPLOYEE_EMPLOYMENT_DATE_FIELD_REQUIRED";
    }
}
